### ISSUE TITLE
filipegiusti Talk

### ISSUE THREAD

**Issue by moacirosa** [HackThursday/hackthursday.github.com#7]
Olá Filipe,

Estamos trabalhando na agenda do evento e gostaríamos de saber quando tu podes palestrar. Acreditamos que em Março, mas já tens um dia? Vamos marcar essa data desde já? Teremos um recesso...

**Comment by filipegiusti** [comment]
Cara, impossível marcar com tanta antecedência. Não sei por onde vou andar.

**Comment by moacirosa** [comment]
Mi mi mi hein! Mais ou menos... Ainda não estamos assinando contrato! Hoaheioahe

**Comment by moacirosa** [comment]
E agora? Tá mais perto? :smile:

**Comment by filipegiusti** [comment]
Claro que não. A próxima data livre é em outubro. Mais de 6 meses de antecedência pra um negócio que era pra ser informal.
Eu falo sobre algo quando alguém desistir. Sou coringa.

**Comment by andreissf** [comment]
certa hora dessas podemos marcar uma conversa informal no cruz de malta,
fugindo um pouco de toda quinta feira...

Acredito que todos temos muito assuntos, duvidas que numa conversa umas vez
por semana ou uma de 15 em 15, ficaria bacana...

Abrass

2013/3/30 Filipe Giusti notifications@github.com

> Claro que não. A próxima data livre é em outubro. Mais de 6 meses de
> antecedência pra um negócio que era pra ser informal.
> Eu falo sobre algo quando alguém desistir. Sou coringa.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HackThursday/hackthursday.github.com/issues/7#issuecomment-15682020
> .

## 

Andrei Silva

**Comment by moacirosa** [comment]
:star:  :smile:

**Comment by krolow** [comment]
+1 Para um churrasco informal @andreissf

**Comment by moacirosa** [comment]
:+1: Para churrasco na casa do @krolow

**Comment by andreissf** [comment]
quando vai rolar?

On Mon, Apr 8, 2013 at 7:05 PM, Moacir Rosa notifications@github.comwrote:

> [image: :+1:] Para churrasco na casa do @krolowhttps://github.com/krolow
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HackThursday/hackthursday.github.com/issues/7#issuecomment-16082043
> .

## 

Andrei Silva
